apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: app
        image: gcr.io/blog-project-228815/toptal-blog
        ports:
        - containerPort: 80
